export type IssueCategory = 'pothole' | 'streetlight' | 'garbage' | 'water' | 'sidewalk' | 'vegetation' | 'other';
export type IssueStatus = 'reported' | 'acknowledged' | 'in-progress' | 'resolved';
export type SeverityLevel = 'low' | 'medium' | 'high' | 'critical';

export interface Issue {
  id: string;
  title: string;
  description: string;
  latitude: number;
  longitude: number;
  category: IssueCategory;
  status: IssueStatus;
  severity: SeverityLevel;
  reportedBy: string;
  reportedAt: Date;
  imageUrl?: string;
  verifications: number;
  updatedAt: Date;
  assignedTo?: string;
  resolutionDate?: Date;
}

export interface User {
  id: string;
  name: string;
  email: string;
  avatar: string;
  issuesReported: number;
  trustScore: number;
  joinedAt: Date;
  isAuthority: boolean;
}

export interface MetricValue {
  date: string;
  value: number;
  target: number;
}

// Mock users (including authority staff)
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    avatar: '👩‍🦰',
    issuesReported: 28,
    trustScore: 92,
    joinedAt: new Date('2024-01-15'),
    isAuthority: false,
  },
  {
    id: '2',
    name: 'Rajesh Kumar',
    email: 'rajesh@example.com',
    avatar: '👨‍💼',
    issuesReported: 45,
    trustScore: 87,
    joinedAt: new Date('2023-11-20'),
    isAuthority: false,
  },
  {
    id: '3',
    name: 'Anaya Desai',
    email: 'anaya@example.com',
    avatar: '👩‍🔬',
    issuesReported: 32,
    trustScore: 95,
    joinedAt: new Date('2024-02-10'),
    isAuthority: false,
  },
  {
    id: '4',
    name: 'Vikram Singh',
    email: 'vikram@example.com',
    avatar: '👨‍💻',
    issuesReported: 51,
    trustScore: 89,
    joinedAt: new Date('2023-10-05'),
    isAuthority: false,
  },
  {
    id: '5',
    name: 'Meera Patel',
    email: 'meera@example.com',
    avatar: '👩‍🌾',
    issuesReported: 19,
    trustScore: 78,
    joinedAt: new Date('2024-03-01'),
    isAuthority: false,
  },
  {
    id: '6',
    name: 'Arjun Nair',
    email: 'arjun@example.com',
    avatar: '👨‍🚒',
    issuesReported: 12,
    trustScore: 85,
    joinedAt: new Date('2024-01-25'),
    isAuthority: false,
  },
  {
    id: '7',
    name: 'Deepika Rao',
    email: 'deepika@example.com',
    avatar: '👩‍⚖️',
    issuesReported: 67,
    trustScore: 91,
    joinedAt: new Date('2023-09-12'),
    isAuthority: false,
  },
  {
    id: '8',
    name: 'Sameer Khan',
    email: 'sameer@example.com',
    avatar: '👨‍🏫',
    issuesReported: 38,
    trustScore: 88,
    joinedAt: new Date('2024-02-28'),
    isAuthority: false,
  },
  {
    id: '9',
    name: 'Neha Gupta',
    email: 'neha@example.com',
    avatar: '👩‍🎨',
    issuesReported: 24,
    trustScore: 82,
    joinedAt: new Date('2024-01-08'),
    isAuthority: false,
  },
  {
    id: '10',
    name: 'Rohan Verma',
    email: 'rohan@example.com',
    avatar: '👨‍✈️',
    issuesReported: 55,
    trustScore: 86,
    joinedAt: new Date('2023-12-15'),
    isAuthority: false,
  },
  {
    id: '11',
    name: 'Sneha Joshi',
    email: 'sneha@example.com',
    avatar: '👩‍💍',
    issuesReported: 31,
    trustScore: 84,
    joinedAt: new Date('2024-02-03'),
    isAuthority: false,
  },
  {
    id: '12',
    name: 'Aditya Singh',
    email: 'aditya@example.com',
    avatar: '👨‍🏭',
    issuesReported: 43,
    trustScore: 79,
    joinedAt: new Date('2024-01-18'),
    isAuthority: false,
  },
  {
    id: '13',
    name: 'Kavya Menon',
    email: 'kavya@example.com',
    avatar: '👩‍🔧',
    issuesReported: 26,
    trustScore: 81,
    joinedAt: new Date('2024-03-05'),
    isAuthority: false,
  },
  {
    id: '14',
    name: 'Sanjay Yadav',
    email: 'sanjay@example.com',
    avatar: '👨‍🍳',
    issuesReported: 18,
    trustScore: 77,
    joinedAt: new Date('2024-02-12'),
    isAuthority: false,
  },
  {
    id: '15',
    name: 'Divya Iyer',
    email: 'divya@example.com',
    avatar: '👩‍🚀',
    issuesReported: 71,
    trustScore: 93,
    joinedAt: new Date('2023-11-02'),
    isAuthority: false,
  },
];

// Mock issues across different areas
export const mockIssues: Issue[] = [
  {
    id: '1',
    title: 'Large pothole on Main Street',
    description: 'Dangerous pothole affecting traffic near the market',
    latitude: 28.6139,
    longitude: 77.2090,
    category: 'pothole',
    status: 'in-progress',
    severity: 'high',
    reportedBy: 'Priya Sharma',
    reportedAt: new Date('2024-06-15'),
    imageUrl: 'https://via.placeholder.com/200?text=Pothole',
    verifications: 12,
    updatedAt: new Date('2024-06-20'),
    assignedTo: 'Maintenance Team A',
  },
  {
    id: '2',
    title: 'Broken streetlight near park',
    description: 'Streetlight not working, area is dark at night',
    latitude: 28.6200,
    longitude: 77.2150,
    category: 'streetlight',
    status: 'acknowledged',
    severity: 'medium',
    reportedBy: 'Rajesh Kumar',
    reportedAt: new Date('2024-06-18'),
    imageUrl: 'https://via.placeholder.com/200?text=Streetlight',
    verifications: 8,
    updatedAt: new Date('2024-06-19'),
  },
  {
    id: '3',
    title: 'Garbage accumulation on street',
    description: 'Municipal waste not collected for 3 days',
    latitude: 28.6100,
    longitude: 77.2050,
    category: 'garbage',
    status: 'resolved',
    severity: 'medium',
    reportedBy: 'Anaya Desai',
    reportedAt: new Date('2024-06-10'),
    imageUrl: 'https://via.placeholder.com/200?text=Garbage',
    verifications: 15,
    updatedAt: new Date('2024-06-17'),
    resolutionDate: new Date('2024-06-17'),
  },
  {
    id: '4',
    title: 'Water leakage from pipeline',
    description: 'Water pipe bursting near intersection, water wastage',
    latitude: 28.6180,
    longitude: 77.2120,
    category: 'water',
    status: 'in-progress',
    severity: 'critical',
    reportedBy: 'Vikram Singh',
    reportedAt: new Date('2024-06-19'),
    imageUrl: 'https://via.placeholder.com/200?text=Water',
    verifications: 22,
    updatedAt: new Date('2024-06-20'),
    assignedTo: 'Water Authority',
  },
  {
    id: '5',
    title: 'Broken sidewalk causing trip hazard',
    description: 'Multiple elderly residents at risk',
    latitude: 28.6160,
    longitude: 77.2110,
    category: 'sidewalk',
    status: 'acknowledged',
    severity: 'high',
    reportedBy: 'Meera Patel',
    reportedAt: new Date('2024-06-16'),
    imageUrl: 'https://via.placeholder.com/200?text=Sidewalk',
    verifications: 18,
    updatedAt: new Date('2024-06-18'),
  },
  {
    id: '6',
    title: 'Overgrown vegetation blocking road',
    description: 'Tree branches obscuring traffic signs',
    latitude: 28.6140,
    longitude: 77.2130,
    category: 'vegetation',
    status: 'resolved',
    severity: 'low',
    reportedBy: 'Arjun Nair',
    reportedAt: new Date('2024-06-08'),
    imageUrl: 'https://via.placeholder.com/200?text=Vegetation',
    verifications: 5,
    updatedAt: new Date('2024-06-14'),
    resolutionDate: new Date('2024-06-14'),
  },
  {
    id: '7',
    title: 'Missing drain cover hazard',
    description: 'Uncovered drain hole near school',
    latitude: 28.6220,
    longitude: 77.2170,
    category: 'other',
    status: 'acknowledged',
    severity: 'critical',
    reportedBy: 'Deepika Rao',
    reportedAt: new Date('2024-06-17'),
    imageUrl: 'https://via.placeholder.com/200?text=Drain',
    verifications: 25,
    updatedAt: new Date('2024-06-19'),
  },
  {
    id: '8',
    title: 'Pothole on residential street',
    description: 'Affects local residents daily',
    latitude: 28.6170,
    longitude: 77.2095,
    category: 'pothole',
    status: 'reported',
    severity: 'low',
    reportedBy: 'Sameer Khan',
    reportedAt: new Date('2024-06-20'),
    imageUrl: 'https://via.placeholder.com/200?text=Pothole2',
    verifications: 3,
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: '9',
    title: 'Multiple broken streetlights',
    description: 'Dark street affecting safety in evening',
    latitude: 28.6125,
    longitude: 77.2085,
    category: 'streetlight',
    status: 'in-progress',
    severity: 'medium',
    reportedBy: 'Neha Gupta',
    reportedAt: new Date('2024-06-14'),
    imageUrl: 'https://via.placeholder.com/200?text=Lights',
    verifications: 10,
    updatedAt: new Date('2024-06-20'),
    assignedTo: 'Electrical Maintenance',
  },
  {
    id: '10',
    title: 'Sewage overflow near market',
    description: 'Health hazard affecting public',
    latitude: 28.6145,
    longitude: 77.2105,
    category: 'garbage',
    status: 'in-progress',
    severity: 'critical',
    reportedBy: 'Rohan Verma',
    reportedAt: new Date('2024-06-19'),
    imageUrl: 'https://via.placeholder.com/200?text=Sewage',
    verifications: 31,
    updatedAt: new Date('2024-06-20'),
    assignedTo: 'Sanitation Division',
  },
  // Additional issues for better map coverage (static, deterministic)
  {
    id: '11',
    title: 'Pothole',
    description: 'Issue reported by community member',
    latitude: 28.6139,
    longitude: 77.2090,
    category: 'pothole',
    status: 'reported',
    severity: 'low',
    reportedBy: 'Priya Sharma',
    reportedAt: new Date(2024, 5, 20),
    imageUrl: 'https://via.placeholder.com/200?text=Issue11',
    verifications: 5,
    updatedAt: new Date(2024, 5, 20),
  },
  {
    id: '12',
    title: 'Broken light',
    description: 'Issue reported by community member',
    latitude: 28.6149,
    longitude: 77.2100,
    category: 'streetlight',
    status: 'acknowledged',
    severity: 'medium',
    reportedBy: 'Rajesh Kumar',
    reportedAt: new Date(2024, 5, 19),
    imageUrl: 'https://via.placeholder.com/200?text=Issue12',
    verifications: 12,
    updatedAt: new Date(2024, 5, 19),
  },
  {
    id: '13',
    title: 'Trash pile',
    description: 'Issue reported by community member',
    latitude: 28.6129,
    longitude: 77.2080,
    category: 'garbage',
    status: 'in-progress',
    severity: 'high',
    reportedBy: 'Anaya Desai',
    reportedAt: new Date(2024, 5, 18),
    imageUrl: 'https://via.placeholder.com/200?text=Issue13',
    verifications: 19,
    updatedAt: new Date(2024, 5, 18),
    assignedTo: 'Maintenance Team A',
  },
  {
    id: '14',
    title: 'Water leak',
    description: 'Issue reported by community member',
    latitude: 28.6159,
    longitude: 77.2120,
    category: 'water',
    status: 'resolved',
    severity: 'critical',
    reportedBy: 'Vikram Singh',
    reportedAt: new Date(2024, 5, 17),
    imageUrl: 'https://via.placeholder.com/200?text=Issue14',
    verifications: 26,
    updatedAt: new Date(2024, 5, 17),
    resolutionDate: new Date(2024, 5, 17),
  },
  {
    id: '15',
    title: 'Cracked pavement',
    description: 'Issue reported by community member',
    latitude: 28.6119,
    longitude: 77.2070,
    category: 'sidewalk',
    status: 'reported',
    severity: 'medium',
    reportedBy: 'Meera Patel',
    reportedAt: new Date(2024, 5, 16),
    imageUrl: 'https://via.placeholder.com/200?text=Issue15',
    verifications: 8,
    updatedAt: new Date(2024, 5, 16),
  },
  {
    id: '16',
    title: 'Dead tree',
    description: 'Issue reported by community member',
    latitude: 28.6169,
    longitude: 77.2110,
    category: 'vegetation',
    status: 'acknowledged',
    severity: 'low',
    reportedBy: 'Arjun Nair',
    reportedAt: new Date(2024, 5, 15),
    imageUrl: 'https://via.placeholder.com/200?text=Issue16',
    verifications: 3,
    updatedAt: new Date(2024, 5, 15),
  },
  {
    id: '17',
    title: 'Graffiti',
    description: 'Issue reported by community member',
    latitude: 28.6109,
    longitude: 77.2060,
    category: 'other',
    status: 'in-progress',
    severity: 'low',
    reportedBy: 'Priya Sharma',
    reportedAt: new Date(2024, 5, 14),
    imageUrl: 'https://via.placeholder.com/200?text=Issue17',
    verifications: 6,
    updatedAt: new Date(2024, 5, 14),
    assignedTo: 'Maintenance Team B',
  },
  {
    id: '18',
    title: 'Manhole cover',
    description: 'Issue reported by community member',
    latitude: 28.6179,
    longitude: 77.2130,
    category: 'pothole',
    status: 'resolved',
    severity: 'medium',
    reportedBy: 'Rajesh Kumar',
    reportedAt: new Date(2024, 5, 13),
    imageUrl: 'https://via.placeholder.com/200?text=Issue18',
    verifications: 14,
    updatedAt: new Date(2024, 5, 13),
    resolutionDate: new Date(2024, 5, 13),
  },
  {
    id: '19',
    title: 'Pothole',
    description: 'Issue reported by community member',
    latitude: 28.6139,
    longitude: 77.2100,
    category: 'pothole',
    status: 'reported',
    severity: 'high',
    reportedBy: 'Anaya Desai',
    reportedAt: new Date(2024, 5, 12),
    imageUrl: 'https://via.placeholder.com/200?text=Issue19',
    verifications: 11,
    updatedAt: new Date(2024, 5, 12),
  },
  {
    id: '20',
    title: 'Broken light',
    description: 'Issue reported by community member',
    latitude: 28.6149,
    longitude: 77.2080,
    category: 'streetlight',
    status: 'acknowledged',
    severity: 'low',
    reportedBy: 'Vikram Singh',
    reportedAt: new Date(2024, 5, 11),
    imageUrl: 'https://via.placeholder.com/200?text=Issue20',
    verifications: 9,
    updatedAt: new Date(2024, 5, 11),
  },
  {
    id: '21',
    title: 'Trash pile',
    description: 'Issue reported by community member',
    latitude: 28.6129,
    longitude: 77.2110,
    category: 'garbage',
    status: 'in-progress',
    severity: 'medium',
    reportedBy: 'Meera Patel',
    reportedAt: new Date(2024, 5, 10),
    imageUrl: 'https://via.placeholder.com/200?text=Issue21',
    verifications: 17,
    updatedAt: new Date(2024, 5, 10),
    assignedTo: 'Maintenance Team A',
  },
  {
    id: '22',
    title: 'Water leak',
    description: 'Issue reported by community member',
    latitude: 28.6159,
    longitude: 77.2090,
    category: 'water',
    status: 'reported',
    severity: 'critical',
    reportedBy: 'Arjun Nair',
    reportedAt: new Date(2024, 5, 9),
    imageUrl: 'https://via.placeholder.com/200?text=Issue22',
    verifications: 24,
    updatedAt: new Date(2024, 5, 9),
  },
  {
    id: '23',
    title: 'Cracked pavement',
    description: 'Issue reported by community member',
    latitude: 28.6119,
    longitude: 77.2120,
    category: 'sidewalk',
    status: 'acknowledged',
    severity: 'high',
    reportedBy: 'Priya Sharma',
    reportedAt: new Date(2024, 5, 8),
    imageUrl: 'https://via.placeholder.com/200?text=Issue23',
    verifications: 7,
    updatedAt: new Date(2024, 5, 8),
  },
  {
    id: '24',
    title: 'Dead tree',
    description: 'Issue reported by community member',
    latitude: 28.6169,
    longitude: 77.2070,
    category: 'vegetation',
    status: 'in-progress',
    severity: 'low',
    reportedBy: 'Rajesh Kumar',
    reportedAt: new Date(2024, 5, 7),
    imageUrl: 'https://via.placeholder.com/200?text=Issue24',
    verifications: 4,
    updatedAt: new Date(2024, 5, 7),
    assignedTo: 'Maintenance Team B',
  },
  {
    id: '25',
    title: 'Graffiti',
    description: 'Issue reported by community member',
    latitude: 28.6109,
    longitude: 77.2100,
    category: 'other',
    status: 'resolved',
    severity: 'medium',
    reportedBy: 'Anaya Desai',
    reportedAt: new Date(2024, 5, 6),
    imageUrl: 'https://via.placeholder.com/200?text=Issue25',
    verifications: 13,
    updatedAt: new Date(2024, 5, 6),
    resolutionDate: new Date(2024, 5, 6),
  },
  {
    id: '26',
    title: 'Manhole cover',
    description: 'Issue reported by community member',
    latitude: 28.6179,
    longitude: 77.2080,
    category: 'pothole',
    status: 'reported',
    severity: 'low',
    reportedBy: 'Vikram Singh',
    reportedAt: new Date(2024, 5, 5),
    imageUrl: 'https://via.placeholder.com/200?text=Issue26',
    verifications: 10,
    updatedAt: new Date(2024, 5, 5),
  },
  {
    id: '27',
    title: 'Pothole',
    description: 'Issue reported by community member',
    latitude: 28.6139,
    longitude: 77.2070,
    category: 'pothole',
    status: 'acknowledged',
    severity: 'medium',
    reportedBy: 'Meera Patel',
    reportedAt: new Date(2024, 5, 4),
    imageUrl: 'https://via.placeholder.com/200?text=Issue27',
    verifications: 15,
    updatedAt: new Date(2024, 5, 4),
  },
  {
    id: '28',
    title: 'Broken light',
    description: 'Issue reported by community member',
    latitude: 28.6149,
    longitude: 77.2120,
    category: 'streetlight',
    status: 'in-progress',
    severity: 'high',
    reportedBy: 'Arjun Nair',
    reportedAt: new Date(2024, 5, 3),
    imageUrl: 'https://via.placeholder.com/200?text=Issue28',
    verifications: 20,
    updatedAt: new Date(2024, 5, 3),
    assignedTo: 'Maintenance Team A',
  },
  {
    id: '29',
    title: 'Trash pile',
    description: 'Issue reported by community member',
    latitude: 28.6129,
    longitude: 77.2090,
    category: 'garbage',
    status: 'reported',
    severity: 'low',
    reportedBy: 'Priya Sharma',
    reportedAt: new Date(2024, 5, 2),
    imageUrl: 'https://via.placeholder.com/200?text=Issue29',
    verifications: 2,
    updatedAt: new Date(2024, 5, 2),
  },
  {
    id: '30',
    title: 'Water leak',
    description: 'Issue reported by community member',
    latitude: 28.6159,
    longitude: 77.2110,
    category: 'water',
    status: 'acknowledged',
    severity: 'critical',
    reportedBy: 'Rajesh Kumar',
    reportedAt: new Date(2024, 5, 1),
    imageUrl: 'https://via.placeholder.com/200?text=Issue30',
    verifications: 30,
    updatedAt: new Date(2024, 5, 1),
  },
];

// Mock metrics data for impact dashboard
export const mockMetrics = {
  averageResolutionTime: [
    { date: 'Jun 1', value: 8.2, target: 5 },
    { date: 'Jun 5', value: 7.8, target: 5 },
    { date: 'Jun 10', value: 6.5, target: 5 },
    { date: 'Jun 15', value: 5.9, target: 5 },
    { date: 'Jun 20', value: 5.2, target: 5 },
  ],
  resolutionRate: [
    { date: 'Jun 1', value: 45, target: 70 },
    { date: 'Jun 5', value: 52, target: 70 },
    { date: 'Jun 10', value: 61, target: 70 },
    { date: 'Jun 15', value: 68, target: 70 },
    { date: 'Jun 20', value: 72, target: 70 },
  ],
  communityEngagement: [
    { date: 'Jun 1', value: 240, target: 500 },
    { date: 'Jun 5', value: 380, target: 500 },
    { date: 'Jun 10', value: 520, target: 500 },
    { date: 'Jun 15', value: 620, target: 500 },
    { date: 'Jun 20', value: 742, target: 500 },
  ],
  reportAccuracy: [
    { date: 'Jun 1', value: 82, target: 90 },
    { date: 'Jun 5', value: 84, target: 90 },
    { date: 'Jun 10', value: 86, target: 90 },
    { date: 'Jun 15', value: 87, target: 90 },
    { date: 'Jun 20', value: 88, target: 90 },
  ],
};

export const categoryIcons: Record<IssueCategory, string> = {
  pothole: '🕳️',
  streetlight: '💡',
  garbage: '🗑️',
  water: '💧',
  sidewalk: '🚶',
  vegetation: '🌳',
  other: '⚠️',
};

export const categoryLabels: Record<IssueCategory, string> = {
  pothole: 'Pothole',
  streetlight: 'Street Light',
  garbage: 'Garbage',
  water: 'Water Issue',
  sidewalk: 'Sidewalk',
  vegetation: 'Vegetation',
  other: 'Other',
};

export const severityColors: Record<SeverityLevel, string> = {
  low: '#10b981',
  medium: '#f59e0b',
  high: '#ef4444',
  critical: '#991b1b',
};

export const statusLabels: Record<IssueStatus, string> = {
  reported: 'Reported',
  acknowledged: 'Acknowledged',
  'in-progress': 'In Progress',
  resolved: 'Resolved',
};
